Website update
lilykuong/lilykuong.github.io pull request #3
Opened 2017-12-23 17:44 UTC by lilykuong

First attempt at having a nice (and mostly professional) looking website. Updates definitely coming soon, but a good starting point nonetheless.

2017-12-23 18:10 UTC, bm1549 requested changes
The page is riddled with needless `id`s when classes seem like the clear alternative. There's also a bunch of duplication in your css.

You'll want to download and host all of the content you're going to use, such as images, js, css, etc.

Minify all of your CSS/JS/(HTML?) before submitting this. Having everything minified keeps the webpage loading fast and keeps https://developers.google.com/speed/pagespeed/insights/ happy

2017-12-23 18:10 UTC, bm1549 commented on scripts/script.js
> +/**
What's up with this spacing? this isn't tabbed, but everything below is

2017-12-23 18:10 UTC, bm1549 commented on scripts/script.js
> +	var fact1 = "In college, I was the president, vice president, \
No need to set `var`s here, just use the array to start

2017-12-23 18:10 UTC, bm1549 commented on scripts/script.js
> +	var i = 1;
Pretty sure there's a JS circular array (or similar) you could use for this instead of playing with the index. Not required, but it's a nice to have.

2017-12-23 18:10 UTC, bm1549 commented on scripts/script.js
> +	var currFact = document.getElementById("fun-fact");
I'd put `"fun-fact"` in a const

2017-12-23 18:10 UTC, bm1549 commented on scripts/script.js
> +	}, 7000)
Magic number 👎

2017-12-23 18:10 UTC, bm1549 commented on scripts/script.js
> +	Change the color of the progess bar for CSS and being a wonderful human
Shouldn't this go in CSS/HTML? Isn't this just an iife, so surely it can be made static

2017-12-23 18:10 UTC, bm1549 commented on styles/style-large.css
> +/**
Spacing?

2017-12-23 18:10 UTC, bm1549 commented on styles/style-large.css
> +    @media(min-width: 801px){
Most of this is duplicated with the above. Let's clean this up a bit to make everything more maintainable in the future

2017-12-23 18:10 UTC, bm1549 commented on styles/style-large.css
> +        "https://www.digitalplatforms.co.za/wp-content/uploads/2015/11/Website-Design-Background.png");
If this site changes its contents, you'll lose this image. Let's host this off Github as well. Just keep track of the source url just in case

2017-12-23 18:10 UTC, bm1549 commented on styles/style-large.css
> +    .body{
Why not just apply this to the tag `body`? Same with `h3` and `h4` below

2017-12-23 18:10 UTC, bm1549 commented on styles/style-small.css
> +    @media(max-width: 400px){
Same comment

2017-12-23 18:10 UTC, bm1549 commented on styles/style-small.css
> +  to be changed for window sizes with a width of 600px or smaller.
`400px or smaller`

2017-12-23 18:10 UTC, bm1549 commented on styles/style-small.css
> + /**
Seems like this could have been a single file since most of the logic is the same

2017-12-23 18:10 UTC, bm1549 commented on styles/style-small.css
> +
??? spacing

2017-12-23 18:10 UTC, bm1549 commented on styles/style.css
> +    .navbar-nav  li a:hover {
Extra space between `nav` and `li`

2017-12-23 18:10 UTC, bm1549 commented on styles/style.css
> +  .progress-bar-css{
Names are kinda weird here

2017-12-23 18:10 UTC, bm1549 commented on styles/style.css
> +  #contact{
Should we be using `id`'s here?

2017-12-23 18:10 UTC, bm1549 commented on styles/style.css
> +  .progress-bar-css{
Usually there's a space between the class name and the `{`

2017-12-23 18:10 UTC, bm1549 commented on styles/style.css
> +      color:rgb(66, 133, 243);
According to a quick Google search https://www.google.com/search?q=linkedin+logo+color+code&rlz=1C5CHFA_enUS724US727&oq=linkedin+logo+color+code&aqs=chrome..69i57.3586j0j1&sourceid=chrome&ie=UTF-8

LinkedIn's color is #0077B5, let's use that here instead

2017-12-23 18:10 UTC, bm1549 commented on styles/style.css
> +      background-color: white;
What color is this guy?

2017-12-23 18:10 UTC, bm1549 commented on styles/style.css
> +      }
`\n` at EOF

2017-12-23 18:10 UTC, bm1549 commented on styles/style.css
> +        background-color:rgb(112, 114, 115);
Use `#` colors

2017-12-23 18:10 UTC, bm1549 commented on website.html
> +    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
Host your own bootstrap and jquery so you're impervious to changes on the hosting domain

2017-12-23 18:10 UTC, bm1549 commented on website.html
> +
Lotso spaces here

2017-12-23 18:10 UTC, bm1549 commented on website.html
> +    <link rel="stylesheet" type="text/css" media="(max-width:600px" href = "styles/style-small.css">
Waddap with that `(`?

2017-12-23 18:10 UTC, bm1549 commented on website.html
> +    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC|Inconsolata|Merriweather|Open+Sans|Source+Sans+Pro" rel="stylesheet">
Host this

2017-12-23 18:10 UTC, bm1549 commented on website.html
> +    <script src="https://use.fontawesome.com/5544a728a0.js"></script>
Host this

2017-12-23 18:10 UTC, bm1549 commented on website.html
> +                    <li><a href="software_engineer_resume.pdf" target="_blank">Resume</a></li>
Up to you, but maybe have this at the end so people can click through and get let out at the end

2017-12-24 12:39 UTC, lilykuong commented on scripts/script.js
> +/**
done

2017-12-24 12:39 UTC, lilykuong commented on scripts/script.js
> +	var fact1 = "In college, I was the president, vice president, \
done

2017-12-24 12:39 UTC, lilykuong commented on scripts/script.js
> +	var currFact = document.getElementById("fun-fact");
Was not changed. fun-fact is being changed.

2017-12-24 12:40 UTC, lilykuong commented on scripts/script.js
> +	}, 7000)
done

2017-12-24 12:40 UTC, lilykuong commented on scripts/script.js
> +	Change the color of the progess bar for CSS and being a wonderful human
done

2017-12-24 23:08 UTC, bm1549 requested changes
One JS change and get rid of all of the extra ids and classes in your HTML that are no longer needed

2017-12-24 23:08 UTC, bm1549 commented on scripts/script.js
> +const FACT_CHANGE_INTERVAL = 7000;
Super minor, but let's put this into an iife

https://en.wikipedia.org/wiki/Immediately-invoked_function_expression

2017-12-24 23:13 UTC, bm1549 commented
Minifying CSS/HTML/JS: https://developers.google.com/speed/docs/insights/MinifyResources

Optimizing images: https://developers.google.com/speed/docs/insights/OptimizeImages

2017-12-25 00:57 UTC, bm1549 approved these changes

2017-12-25 00:58 UTC, merged